name: melodilambda
version: 0.1.0.0
github: "yoptabyte/melodilambda"
license: BSD3
author: "yoptabyte"
maintainer: "yoptabyte@example.com"

extra-source-files:
- README.md

description: Telegram bot for converting YouTube videos to audio tracks

dependencies:
- telegram-bot-api >= 6.7
- base >= 4.7 && < 5
- telegram-bot-simple >= 0.12
- text >= 1.2
- bytestring >= 0.10
- process >= 1.6
- directory >= 1.3
- filepath >= 1.4
- http-client >= 0.7
- http-client-tls >= 0.3
- aeson >= 2.0
- async >= 2.2
- stm >= 2.5
- time >= 1.9
- transformers >= 0.5
- servant-client >= 0.19
- dotenv >= 0.9

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  melodilambda:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -O2
